ARG ELASTICSEARCH_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install <name|url>
